export const FETCH_PRODUCT_DATA = "FETCH_PRODUCT_DATA";
export const LOADING = "LOADING";
export const SHOW_ERROR = "SHOW_ERROR";
export const FETCH_PRODUCT_BYID = "FETCH_PRODUCT_BYID";
export const ADD_CART = "ADD_CART";
export const REMOVE_CART = "REMOVE_CART";
export const ADD_QUENTITY = "ADD_QUENTITY";
export const REMOVE_QUENTITY = "REMOVE_QUENTITY";
